# Site settings
title: Tirthankar Chakravarty
email: tirthankar.lists@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Tirthankar14
github_username:  tchakravarty

# Build settings
markdown: kramdown


comments :
  provider : disqus
  disqus :
    short_name : tchakravarty
